### ISSUE TITLE
leetcode #35 - unnecessary +1?

### ISSUE THREAD

**Issue by purplegerbil** [jiadaizhao/LeetCode#4]
while (start + 1< end)

why +1?  it passes without this.

**Comment by jiadaizhao** [comment]
It's just a template, see https://leetcode.com/explore/learn/card/binary-search/135/template-iii/936/. You can apply this template to almost any binary search problem, although sometimes not so efficient as other templates. It's easiest to implement for beginners. I improved solution in python later.
